#pragma once

#include "JSystem/J3DGraphBase/J3DAnimation.h"
#include "JSystem/J3DGraphBase/J3DDrawBuffer.h"
//#include "JSystem/J3DGraphBase/J3DGD.h"
#include "JSystem/J3DGraphBase/J3DGXColor.h"
//#include "JSystem/J3DGraphBase/J3DJoint.h"
#include "JSystem/J3DGraphBase/J3DJointTree.h"
#include "JSystem/J3DGraphBase/J3DMaterial.h"
#include "JSystem/J3DGraphBase/J3DMaterialAttach.h"
#include "JSystem/J3DGraphBase/J3DModel.h"
#include "JSystem/J3DGraphBase/J3DModelData.h"
#include "JSystem/J3DGraphBase/J3DMtxBuffer.h"
//#include "JSystem/J3DGraphBase/J3DPacket.h"
//#include "JSystem/J3DGraphBase/J3DSys.h"
//#include "JSystem/J3DGraphBase/J3DTransform.h"
#include "JSystem/J3DGraphBase/J3DVertex.h"
