#pragma once

/* FINISHED */

namespace MR {
    enum MovementType {
        MovementType_00                    = 0x00, // never executed
        MovementType_StopSceneDelayRequest = 0x01,
        MovementType_Camera                = 0x02,
        MovementType_ScreenEffect          = 0x03,
        MovementType_ClippingDirector      = 0x04,
        MovementType_SensorHitChecker      = 0x05,
        MovementType_MsgSharedGroup        = 0x06,
        MovementType_07                    = 0x07,
        MovementType_08                    = 0x08, // never executed
        MovementType_AudCameraWatcher      = 0x09,
        MovementType_TalkDirector          = 0x0A,
        MovementType_DemoDirector          = 0x0B,
        MovementType_0C                    = 0x0C,
        MovementType_AreaObj               = 0x0D,
        MovementType_Layout                = 0x0E,
        MovementType_LayoutDecoration      = 0x0F,
        MovementType_WipeLayout            = 0x10,
        MovementType_LayoutOnPause         = 0x11,
        MovementType_12                    = 0x12,
        MovementType_13                    = 0x13,
        MovementType_MirrorCamera          = 0x14,
        MovementType_ImageEffect           = 0x15,
        MovementType_AudEffectDirector     = 0x16,
        MovementType_AudBgmConductor       = 0x17,
        MovementType_CameraCover           = 0x18,
        MovementType_SwitchWatcherHolder   = 0x19,
        MovementType_PauseBlur             = 0x1A,
        MovementType_MapParts              = 0x1B,
        MovementType_Planet                = 0x1C,
        MovementType_CollisionMapObj       = 0x1D,
        MovementType_CollisionEnemy        = 0x1E,
        MovementType_CollisionDirector     = 0x1F,
        MovementType_Environment           = 0x20,
        MovementType_MapObj                = 0x21,
        MovementType_MapObjDecoration      = 0x22,
        MovementType_AfterMapObj           = 0x23,
        MovementType_Player                = 0x24,
        MovementType_PlayerDecoration      = 0x25,
        MovementType_PlayerMessenger       = 0x26,
        MovementType_Npc                   = 0x27,
        MovementType_Ride                  = 0x28,
        MovementType_Enemy                 = 0x29,
        MovementType_EnemyDecoration       = 0x2A,
        MovementType_Item                  = 0x2B,
        MovementType_ShadowController      = 0x2C,
        MovementType_SuperDreamer          = 0x2D,
        MovementType_WorldMapInfo          = 0x2E,
        MovementType_WorldMapMiniObj       = 0x2F,
        MovementType_WorldMapIcon          = 0x30,

        MovementType_MaxValue              = 0x31
    };

    enum CalcAnimType {
        CalcAnimType_MapParts              = 0x00,
        CalcAnimType_Planet                = 0x01,
        CalcAnimType_CollisionMapObj       = 0x02,
        CalcAnimType_CollisionEnemy        = 0x03,
        CalcAnimType_Environment           = 0x04,
        CalcAnimType_MapObj                = 0x05,
        CalcAnimType_Npc                   = 0x06,
        CalcAnimType_Ride                  = 0x07,
        CalcAnimType_Enemy                 = 0x08,
        CalcAnimType_Player                = 0x09,
        CalcAnimType_PlayerDecoration      = 0x0A,
        CalcAnimType_MapObjDecoration      = 0x0B,
        CalcAnimType_MirrorMapObj          = 0x0C,
        CalcAnimType_Layout                = 0x0D,
        CalcAnimType_LayoutDecoration      = 0x0E,
        CalcAnimType_Item                  = 0x0F,
        CalcAnimType_10                    = 0x10, // never executed
        CalcAnimType_Particle              = 0x11,
        CalcAnimType_ParticleIgnorePause   = 0x12,
        CalcAnimType_13                    = 0x13,
        CalcAnimType_WorldMapMiniObj       = 0x14,
        CalcAnimType_WorldMapIcon          = 0x15,
        CalcAnimType_16                    = 0x16, // never executed

        CalcAnimType_MaxValue              = 0x17
    };

    enum DrawBufferType {
        DrawBufferType_ClippedMapParts                = 0x00,
        DrawBufferType_BossBussun                     = 0x01,
        DrawBufferType_Sky                            = 0x02,
        DrawBufferType_Air                            = 0x03,
        DrawBufferType_Sun                            = 0x04,
        DrawBufferType_Planet                         = 0x05,
        DrawBufferType_PlanetLow                      = 0x06,
        DrawBufferType_Environment                    = 0x07,
        DrawBufferType_EnvironmentStrongLight         = 0x08,
        DrawBufferType_MapObj                         = 0x09,
        DrawBufferType_MapObjWeakLight                = 0x0A,
        DrawBufferType_MapObjStrongLight              = 0x0B,
        DrawBufferType_NoShadowedMapObj               = 0x0C,
        DrawBufferType_NoShadowedMapObjStrongLight    = 0x0D,
        DrawBufferType_NoSilhouettedMapObj            = 0x0E,
        DrawBufferType_NoSilhouettedMapObjWeakLight   = 0x0F,
        DrawBufferType_NoSilhouettedMapObjStrongLight = 0x10,
        DrawBufferType_Npc                            = 0x11,
        DrawBufferType_Ride                           = 0x12,
        DrawBufferType_Enemy                          = 0x13,
        DrawBufferType_EnemyDecoration                = 0x14,
        DrawBufferType_Player                         = 0x15, // never executed
        DrawBufferType_PlayerDecoration               = 0x16,
        DrawBufferType_GhostMazeMask                  = 0x17,
        DrawBufferType_18                             = 0x18,
        DrawBufferType_19                             = 0x19,
        DrawBufferType_IndirectMapObj                 = 0x1A,
        DrawBufferType_IndirectMapObjStrongLight      = 0x1B,
        DrawBufferType_IndirectNpc                    = 0x1C,
        DrawBufferType_IndirectEnemy                  = 0x1D,
        DrawBufferType_IndirectPlanet                 = 0x1E,
        DrawBufferType_Bloom                          = 0x1F,
        DrawBufferType_TripodBoss                     = 0x20,
        DrawBufferType_Crystal                        = 0x21,
        DrawBufferType_CrystalItem                    = 0x22,
        DrawBufferType_GlaringLight                   = 0x23,
        DrawBufferType_24                             = 0x24,
        DrawBufferType_TimeStopScreenEffect           = 0x25,
        DrawBufferType_StoryBook                      = 0x26,
        DrawBufferType_WorldMapMiniObj                = 0x27,
        DrawBufferType_WorldMapIcon                   = 0x28,
        DrawBufferType_3DModelFor2D                   = 0x29,
        DrawBufferType_2A                             = 0x2A,
        DrawBufferType_SwitchingScreenEffect          = 0x2B,
        DrawBufferType_MirrorMapObj                   = 0x2C,
        DrawBufferType_2D                             = 0x2D, // never executed
        DrawBufferType_2E                             = 0x2E, // never executed
        DrawBufferType_2F                             = 0x2F, // never executed

        DrawBufferType_MaxValue                       = 0x30
    };

    enum DrawType {
        DrawType_SwingRope                = 0x00,
        DrawType_01                       = 0x01,
        DrawType_Creeper                  = 0x02,
        DrawType_03                       = 0x03,
        DrawType_PlantStalk               = 0x04,
        DrawType_Plant                    = 0x05,
        DrawType_Trapeze                  = 0x06,
        DrawType_OceanBowl                = 0x07,
        DrawType_OceanRing                = 0x08,
        DrawType_OceanRingPipeInside      = 0x09,
        DrawType_OceanRingPipeOutside     = 0x0A,
        DrawType_OceanSphere              = 0x0B,
        DrawType_WaterRoad                = 0x0C,
        DrawType_WhirlPool                = 0x0D,
        DrawType_ElectricRail             = 0x0E,
        DrawType_BigBubble                = 0x0F,
        DrawType_BigBubbleGoal            = 0x10,
        DrawType_11                       = 0x11,
        DrawType_SpinDriverPath           = 0x12,
        DrawType_GCapture                 = 0x13,
        DrawType_ClipAreaDropLaser        = 0x14,
        DrawType_SpiderThread             = 0x15,
        DrawType_SpaceCocoon              = 0x16,
        DrawType_17                       = 0x17,
        DrawType_NormalMapObj             = 0x18,
        DrawType_FlexibleSphere           = 0x19,
        DrawType_KirairaChain             = 0x1A,
        DrawType_WaterPlant               = 0x1B,
        DrawType_1C                       = 0x1C,
        DrawType_1D                       = 0x1D,
        DrawType_Flag                     = 0x1E,
        DrawType_1F                       = 0x1F,
        DrawType_20                       = 0x20,
        DrawType_WoodLogBridge            = 0x21,
        DrawType_HipDropStarMove          = 0x22,
        DrawType_DynamicMapObj            = 0x23,
        DrawType_24                       = 0x24,
        DrawType_Player                   = 0x25,
        DrawType_26                       = 0x26,
        DrawType_27                       = 0x27,
        DrawType_MiiFaceParts             = 0x28,
        DrawType_29                       = 0x29,
        DrawType_ShadowSurface            = 0x2A,
        DrawType_ShadowVolume             = 0x2B,
        DrawType_Silhouette               = 0x2C,
        DrawType_2D                       = 0x2D,
        DrawType_ClipArea                 = 0x2E,
        DrawType_FallOutFieldDraw         = 0x2F,
        DrawType_ClipFieldFillDraw        = 0x30, // never executed
        DrawType_CaptureScreenIndirect    = 0x31,
        DrawType_CaptureScreenCamera      = 0x32,
        DrawType_33                       = 0x33,
        DrawType_CenterScreenBlur         = 0x34,
        DrawType_35                       = 0x35,
        DrawType_FurDraw                  = 0x36,
        DrawType_37                       = 0x37,
        DrawType_38                       = 0x38,
        DrawType_BloomEffectPreDraw       = 0x39,
        DrawType_BloomEffectPostDraw      = 0x3A,
        DrawType_3B                       = 0x3B,
        DrawType_ImageEffect              = 0x3C,
        DrawType_DashRing                 = 0x3D,
        DrawType_BrightObj                = 0x3E,
        DrawType_WaterCameraFilter        = 0x3F,
        DrawType_40                       = 0x40,
        DrawType_TimeStopScreenEffect     = 0x41,
        DrawType_PauseBlur                = 0x42,
        DrawType_43                       = 0x43,
        DrawType_44                       = 0x44,
        DrawType_45                       = 0x45,
        DrawType_Layout                   = 0x46,
        DrawType_LayoutDecoration         = 0x47,
        DrawType_LayoutOnPause            = 0x48,
        DrawType_CometScreenFilter        = 0x49,
        DrawType_WipeLayout               = 0x4A,
        DrawType_TalkLayout               = 0x4B,
        DrawType_4C                       = 0x4C,
        DrawType_CinemaFrame              = 0x4D,
        DrawType_GalaxyNamePlate          = 0x4E,
        DrawType_WorldMapInfo             = 0x4F,
        DrawType_50                       = 0x50,
        DrawType_FileSelect               = 0x51,
        DrawType_Particle3D               = 0x52,
        DrawType_ParticleIndirect         = 0x53,
        DrawType_ParticleAfterIndirect    = 0x54,
        DrawType_ParticleWorldMapMiniIcon = 0x55,
        DrawType_Particle2D               = 0x56,
        DrawType_ParticleFor2DModel       = 0x57,
        DrawType_ParticleBloomEffect      = 0x58,
        DrawType_ParticleAfterImageEffect = 0x59,
        DrawType_5A                       = 0x5A,
        DrawType_5B                       = 0x5B,
        DrawType_CameraCover              = 0x5C,

        DrawType_MaxValue                 = 0x5D
    };

    enum CategoryType {
        CategoryList_Auto = -2,
        CategoryList_Null = -1
    };
};
