#pragma once

#include "revolution.h"

class NameObj;

#define SCENE_OBJ_SENSOR_HIT_CHECKER 0 
#define SCENE_OBJ_COLLISION_DIRECTOR 1 
#define SCENE_OBJ_CLIPPING_DIRECTOR 2 
#define SCENE_OBJ_DEMO_DIRECTOR 3 
#define SCENE_OBJ_EVENT_DIRECTOR 4 
#define SCENE_OBJ_EFFECT_SYSTEM 5 
#define SCENE_OBJ_LIGHT_DIRECTOR 6 
#define SCENE_OBJ_SCENE_DATA_INITIALIZER 7 
#define SCENE_OBJ_STAGE_DATA_HOLDER 8 
#define SCENE_OBJ_MESSAGE_SENSOR_HOLDER 9 
#define SCENE_OBJ_STAGE_SWITCH_CONTAINER 10 
#define SCENE_OBJ_SWITCH_WATCHER_HOLDER 11 
#define SCENE_OBJ_AWAKE_CONTROLLER_HOLDER 12 
#define SCENE_OBJ_AREA_OBJ_CONTAINER 13 
#define SCENE_OBJ_LIVE_ACTOR_GROUP_ARRAY 14 
#define SCENE_OBJ_MOVEMENT_ON_OFF_GROUP_HOLDER 15 
#define SCENE_OBJ_CAPTURE_SCREEN_ACTOR 16 
#define SCENE_OBJ_AUD_CAMERA_WATCHER 17 
#define SCENE_OBJ_AUD_EFFECT_DIRECTOR 18 
#define SCENE_OBJ_AUD_BGM_CONDUCTOR 19 
#define SCENE_OBJ_ACTION_SOUND_SYSTEM 20 
#define SCENE_OBJ_MARIO_HOLDER 21 
#define SCENE_OBJ_DELETED_22 22 
#define SCENE_OBJ_MIRROR_CAMERA 23 
#define SCENE_OBJ_CAMERA_CONTEXT 24 
#define SCENE_OBJ_IGNORE_PAUSE_NAME_OBJ 25 
#define SCENE_OBJ_TALK_DIRECTOR 26 
#define SCENE_OBJ_EVENT_SEQUENCER 27 
#define SCENE_OBJ_STOP_SCENE_CONTROLLER 28 
#define SCENE_OBJ_SCENE_NAME_OBJ_MOVEMENT_CONTROLLER 29 
#define SCENE_OBJ_IMAGE_EFFECT_SYSTEM_HOLDER 30 
#define SCENE_OBJ_BLOOM_EFFECT 31 
#define SCENE_OBJ_BLOOM_EFFECT_SIMPLE 32 
#define SCENE_OBJ_SCREEN_BLUR_EFFECT 33 
#define SCENE_OBJ_DEPTH_OF_FIELD_BLUR 34 
#define SCENE_OBJ_POST_FOG 35 
#define SCENE_OBJ_POST_OUTLINE 36 
#define SCENE_OBJ_SCENE_WIPE_HOLDER 37 
#define SCENE_OBJ_PLAYER_ACTION_GUIDANCE 38 
#define SCENE_OBJ_LENS_FLARE_DIRECTOR 39 
#define SCENE_OBJ_FUR_DRAW_MANAGER 40 
#define SCENE_OBJ_PLACEMENT_STATE_CHECKER 41 
#define SCENE_OBJ_NAME_POS_HOLDER 42 
#define SCENE_OBJ_NPC_DIRECTOR 43 
#define SCENE_OBJ_RESOURCE_SHARE 44 
#define SCENE_OBJ_WARP_POD_MGR 45 
#define SCENE_OBJ_CENTER_SCREEN_BLUR 46 
#define SCENE_OBJ_SWITCHING_SCREEN_EFFECT 47 
#define SCENE_OBJ_TIME_STOP_SCREEN_CAPTURE_TEXTURE 48 
#define SCENE_OBJ_TIME_STOP_SCREEN_CAPTURE_EFFECT 49 
#define SCENE_OBJ_SWING_ACTION_WATCHER 50 
#define SCENE_OBJ_51 51 // ワールドマップ
#define SCENE_OBJ_52 52 // ワールドマップ（リザルト指揮）
#define SCENE_OBJ_53 53 // スコアアタックアクセサ
#define SCENE_OBJ_SCORE_RESULT_KEEPER 54 
#define SCENE_OBJ_55 55 // 郵便屋さんシステム
#define SCENE_OBJ_SUPPORT_PLAY_DIRECTOR 56 
#define SCENE_OBJ_ALL_LIVE_ACTOR_GROUP 57 
#define SCENE_OBJ_CAMERA_DIRECTOR 58 
#define SCENE_OBJ_PLANET_GRAVITY_MANAGER 59 
#define SCENE_OBJ_BASE_MATRIX_FOLLOW_TARGET_HOLDER 60 
#define SCENE_OBJ_GAME_SCENE_LAYOUT_HOLDER 61 
#define SCENE_OBJ_DELETED_62 62 
#define SCENE_OBJ_COIN_HOLDER 63 
#define SCENE_OBJ_PURPLE_COIN_HOLDER 64 
#define SCENE_OBJ_COIN_ROTATER 65 
#define SCENE_OBJ_AIR_BUBBLE_HOLDER 66 
#define SCENE_OBJ_KARIKARI_DIRECTOR 67 
#define SCENE_OBJ_STAR_PIECE_DIRECTOR 68 
#define SCENE_OBJ_BEGOMAN_ATTACK_PERMITTER 69 
#define SCENE_OBJ_BIG_FAN_HOLDER 70 
#define SCENE_OBJ_DELETED_71 71 
#define SCENE_OBJ_DELETED_72 72 
#define SCENE_OBJ_DELETED_73 73 
#define SCENE_OBJ_KABOKURI_FIRE_HOLDER 74 
#define SCENE_OBJ_TAKOHEI_INK_HOLDER 75 
#define SCENE_OBJ_SHADOW_CONTROLLER_PARAM 76 
#define SCENE_OBJ_77 77 // 影色セット
#define SCENE_OBJ_SHADOW_VOLUME_DRAW_INIT 78 
#define SCENE_OBJ_SHADOW_SURFACE_DRAW_INIT 79 
#define SCENE_OBJ_SWING_ROPE_GROUP 80 
#define SCENE_OBJ_PLANT_STALK_DRAW_INIT 81 
#define SCENE_OBJ_PLANT_LEAF_DRAW_INIT 82 
#define SCENE_OBJ_TRAPEZE_ROPE_DRAW_INIT 83 
#define SCENE_OBJ_DELETED_84 84 
#define SCENE_OBJ_SPIN_DRIVER_PATH_DRAW_INIT 85 
#define SCENE_OBJ_NOTE_GROUP 86 
#define SCENE_OBJ_CLIP_AREA_DROP_HOLDER 87 
#define SCENE_OBJ_FALL_OUT_FIELD_DRAW 88 
#define SCENE_OBJ_CLIP_FIELD_FILL_DRAW 89 
#define SCENE_OBJ_DELETED_90 90 
#define SCENE_OBJ_CLIP_AREA_HOLDER 91 
#define SCENE_OBJ_SNOW_STEP_HOLDER 92 
#define SCENE_OBJ_CLIP_AREA_LIGHT_FRUIT 93 
#define SCENE_OBJ_SCREEN_ALPHA_CAPTURE 94 
#define SCENE_OBJ_MAP_PARTS_RAIL_GUIDE_HOLDER 95 
#define SCENE_OBJ_SPIN_CLOUD_BLOCK_GROUP 96 
#define SCENE_OBJ_G_CAPTURE 97 
#define SCENE_OBJ_SUPPORT_TICO 98 
#define SCENE_OBJ_NAME_OBJ_EXECUTE_HOLDER 99 
#define SCENE_OBJ_ELECTRIC_RAIL_HOLDER 100 
#define SCENE_OBJ_SPIDER_THREAD 101 
#define SCENE_OBJ_QUAKE_EFFECT_GENERATOR 102 
#define SCENE_OBJ_BOWSER_BATTLE_ACCESSOR 103 
#define SCENE_OBJ_DELETED_104 104 
#define SCENE_OBJ_DELETED_105 105 
#define SCENE_OBJ_HEAT_HAZE_DIRECTOR 106 
#define SCENE_OBJ_YELLOW_CHIP_HOLDER 107 
#define SCENE_OBJ_EARTHEN_PIPE_MEDIATOR 108 
#define SCENE_OBJ_PETIT_PORTER_MEDIATOR 109 
#define SCENE_OBJ_DELETED_110 110 
#define SCENE_OBJ_WATER_AREA_HOLDER 111 
#define SCENE_OBJ_WATER_PLANT_DRAW_INIT 112 
#define SCENE_OBJ_RACE_MANAGER 113 
#define SCENE_OBJ_GROUP_CHECK_MANAGER 114 
#define SCENE_OBJ_WATER_PRESSURE_BULLET_HOLDER 115 
#define SCENE_OBJ_FIRE_PRESSURE_BULLET_HOLDER 116 
#define SCENE_OBJ_SUNSHADE_MAP_HOLDER 117 
#define SCENE_OBJ_MII_FACE_PARTS_HOLDER 118 
#define SCENE_OBJ_MII_FACE_ICON_HOLDER 119 
#define SCENE_OBJ_FLUFF_WIND_HOLDER 120 
#define SCENE_OBJ_GALAXY_NAME_PLATE_DRAWER 121 
#define SCENE_OBJ_CINEMA_FRAME 122 
#define SCENE_OBJ_DELETED_123 123 
#define SCENE_OBJ_PLAYER_FOLLOW_PASS 124 
#define SCENE_OBJ_INFERNO_MARIO_MANAGER 125 
#define SCENE_OBJ_PLANET_MAP_CREATOR 126 
#define SCENE_OBJ_PRODUCT_MAP_CREATOR 127 
#define SCENE_OBJ_PRIOR_DRAW_AIR_HOLDER 128 
#define SCENE_OBJ_INFORMATION_OBSERVER 129 
#define SCENE_OBJ_STAFF_ROLL 130 
#define SCENE_OBJ_MAP_PARTS_HOLDER 131 
#define SCENE_OBJ_STAR_LIGHT_AREA_HOLDER 132 
#define SCENE_OBJ_CHANGE_OBJ_HOLDER 133 
#define SCENE_OBJ_DRILL_HOLE_HOLDER 134 
#define SCENE_OBJ_COLLECT_TICO_HOLDER 135 
#define SCENE_OBJ_ICE_METEOR_HOLDER 136 
#define SCENE_OBJ_STORY_BOOK_WARP_DEMO 137 
#define SCENE_OBJ_POPO_STICKING_MANAGER 138 
#define SCENE_OBJ_KOOPA_JR_CASTLE_ACCESSOR 139 
#define SCENE_OBJ_KOOPA_JR_CASTLE_WIND_HOLDER 140 
#define SCENE_OBJ_GLIDER_SHOOTER_BULLET_HOLDER 141 
#define SCENE_OBJ_GHOST_ATTACK_MANAGER 142 
#define SCENE_OBJ_GLI_BIRD_TUTORIAL 143 
#define SCENE_OBJ_PAUSE_BLUR 144 
#define SCENE_OBJ_STAR_PIECE_FLOWER_CONTROLLER 145 
#define SCENE_OBJ_WOOD_BOX_EXTERMINATION_FLAG_HOLDER 146 
#define SCENE_OBJ_MARIO_FACE_SHIP_SWITCH 147 
#define SCENE_OBJ_148 148 // 注目会話デモ指示者
#define SCENE_OBJ_149 149 // NPC紹介デモ参加者ホルダー
#define SCENE_OBJ_150 150 // 会話デモ指示者
#define SCENE_OBJ_MARIO_FACE_SHIP_EVENT_DATA_HOLDER 151 
#define SCENE_OBJ_WII_MESSAGE_BOARD_MAIL_SENDER 152 

class SceneObjHolder {
public:
	SceneObjHolder();

	NameObj* create(int sceneObjId);
	NameObj* getObj(int sceneObjId) const;
	bool isExist(int sceneObjId) const;
	NameObj* newEachObj(int sceneObjId);

	NameObj* mSceneObjs[153];
};

namespace MR {
	NameObj* createSceneObj(int sceneObjId);
	SceneObjHolder* getSceneObjHolder();
	bool isExistSceneObj(int sceneObjId);
};
